**MAMOONA IQBAL**

*C2C LAB - Afternoon 1*

Course: AI/ML

**Assignment 46 — Week 4, Day 1**

**Topic: Pandas**

Data analysis with Pandas.

In [62]:
import pandas as pd

df = pd.read_csv('calories.csv')
df.head(5)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [63]:
print(df.head()) #print first 5 rows

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [64]:
print(df.tail())  #print last 5 rows

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [65]:
print(df.info()) #info about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None

**Assignment 47 — Week 4, Day 1**

**Topic: Pandas**

Pandas data-cleaning techniques.

In [66]:
df.isna().sum()  #count missing values per column

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [67]:
print("Mean:", df["Calories"].mean())
print("Median:", df["Calories"].median())
print("Mode:", df["Calories"].mode())

Mean: 375.79024390243904
Median: 318.6
Mode: 0    300.0
Name: Calories, dtype: float64

In [68]:
#Null Values/Empty Cell:
new_data_frame=df.dropna()
new_data_frame.head(10)  #new dataframe with no empty cell

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [69]:
#Fill null values rows with median
df["Calories"] = df["Calories"].fillna(
    df["Calories"].median()
)

print(df.isnull().sum())

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [70]:
#OR Remove all rows with null values
#df.dropna(inplace=True)

In [49]:
#Check Duplicates:
print(df[df.duplicated()])

#Remove Duplicates if Required:
#df.drop_duplicates(inplace = True)

     Duration  Pulse  Maxpulse  Calories
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
40         45     90       112     180.1
71         60    109       153     387.6
113        45    100       120     225.3
155        60    111       151     368.5

In [71]:
# Wrong data:
#If duration or time is above 120(2 hours) ,repalce the value with 120  OR Rmove it
for d in df.index:
  if df.loc[d, "Duration"] > 120:
    df.loc[d, "Duration"] = 120

In [72]:
# OR: Delete rows where "Duration" is higher than 120:

#for d in df.index:
#  if df.loc[d, "Duration"] > 120:
#    df.drop(d, inplace = True)

**Assignment 48 — Week 4, Day 1**

**Topic: Pandas**

Data correlation with Pandas.

In [73]:
df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.238237 -0.072727  0.819269
Pulse    -0.238237  1.000000  0.786535  0.028099
Maxpulse -0.072727  0.786535  1.000000  0.205172
Calories  0.819269  0.028099  0.205172  1.000000

In [74]:
print("Good Coorelation: Duration and Calories got a 0.922721")
print("Bad Coorelation:  Duration and Maxpulse got a 0.009403")

Good Coorelation: Duration and Calories got a 0.922721
Bad Coorelation:  Duration and Maxpulse got a 0.009403

In [75]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   169.000000
mean    58.579882  107.461538  134.047337   374.098225
std     25.267518   14.510259   16.450434   262.565937
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   253.300000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   384.000000
max    120.000000  159.000000  184.000000  1860.400000

**Assignment 49 — Week 2, Day 4**

**Topic: Statistics**

Calculate mean, median, and mode.

Mean - The average value

Median - The mid point value

Mode - The most common value

In [76]:
import numpy as np
from scipy import stats

In [77]:
#scores:
scores = [86, 70, 98, 90, 92, 70, 78, 66]

mean = np.mean(scores)
median = np.median(scores)
modeVal = stats.mode(scores)

print("Scores List:", scores)
print("Mean:", mean )
print("Median:", median)
print("Mode:", modeVal.mode )

Scores List: [86, 70, 98, 90, 92, 70, 78, 66]
Mean: 81.25
Median: 82.0
Mode: 70

**Assignment 50 — Week 2, Day 5**

**Topic: Statistics**

Calculate standard deviation.

In [78]:
#scores:
scores = [86, 70, 98, 90, 92, 70, 78, 66]
standard_deviation = np.std(scores)

print("Scores List:", scores)
print("Standard Deviation:",round(standard_deviation,3))

Scores List: [86, 70, 98, 90, 92, 70, 78, 66]
Standard Deviation: 11.133