**MAMOONA IQBAL**

*C2C LAB - Afternoon 1*

Course: AI/ML

**Assignment 28 — Week 3, Day 3**

**Topic: NumPy**

Creating NumPy arrays using Python.

In [ ]:
import numpy as np

In [ ]:
array_1D = np.array([10, 20, 30, 40, 50, 60, 70])
print("1D Array:\n", array_1D)
print("Dimensions:", array_1D.ndim)

# 2D Array (Matrix)
array_2D = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\n2D Array:\n", array_2D)
print("Dimensions:", array_2D.ndim)

# 3D Array (Tensor)
array_3D = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("\n3D Array:\n", array_3D)
print("Dimensions:", array_3D.ndim)

1D Array:
 [10 20 30 40 50 60 70]
Dimensions: 1

2D Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3

**Assignment 29 — Week 3, Day 4**

**Topic: NumPy**

NumPy array indexing.

In [ ]:
print("1D:Index 2:", array_1D[2])
print("2D:Element at Row 1,Col 2:", array_2D[1, 2])
print("3D:Element at at block 1, row 0, col 1:", array_3D[1, 0, 1])

1D:Index 2: 30
2D:Element at Row 1,Col 2: 6
3D:Element at at block 1, row 0, col 1: 6

**Assignment 30 — Week 3, Day 4**

**Topic: NumPy**

NumPy array slicing.

In [ ]:
# Slicing 1D array [start:end]
print("1D Array: slice from index 1 to 3:", array_1D[1:3])
print("1D Array: Return every element from index 1 to index 6 with stepsize 2:",array_1D[1:6:2])

# Slicing 2D array: Get first row, columns from index 1 onwards
print("2D Array: row 0, elements from index 1 onwards:", array_2D[0, 1])

# Slicing 2D array: Get all rows, but only column 1
print("3D Array: all rows, column 1:", array_3D[:, 1])

1D Array: slice from index 1 to 3: [20 30]
1D Array: Return every element from index 1 to index 6 with stepsize 2: [20 40 60]
2D Array: row 0, elements from index 1 onwards: 2
3D Array: all rows, column 1: [[3 4]
 [7 8]]

**Assignment 31 — Week 3, Day 4**

**Topic: NumPy**

NumPy data types.

In [ ]:
print("Data type of array_1D:", array_1D.dtype)
print("Data type of array_2D:", array_2D.dtype)
print("Data type of array_3D:", array_3D.dtype)

float_array=np.array([1.5, 2.7, 3.1])
print("Float Array:", float_array, "with dtype:", float_array.dtype)

string_arr = np.array(['Lahore', 'Karachi', 'Islamabad'])
print("String Array:",string_arr,"with dtype:",string_arr.dtype)

Data type of array_1D: int64
Data type of array_2D: int64
Data type of array_3D: int64
Float Array: [1.5 2.7 3.1] with dtype: float64
String Array: ['Lahore' 'Karachi' 'Islamabad'] with dtype: <U9

**Assignment 32 — Week 3, Day 4**

**Topic: NumPy**

NumPy array copying and viewing.

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
print("Original Array:", original_array)
# VIEW: A view shares data with the original array. Changes affect both.
view_arr = original_array.view()
print("View of Original Array:", view_arr)
view_arr[1] = 32
print("Original Array after modifying its VIEW:(2nd member (2) changed):", original_array)

# COPY: Changes do not affect the original.
original_arr = np.array([1, 2, 3, 4, 5])
copy_arr = original_arr.copy()
copy_arr[0] = 345
print("Original Array after modifying its COPY:", original_arr)
print("The COPY itself changed:", copy_arr)

Original Array: [1 2 3 4 5]
View of Original Array: [1 2 3 4 5]
Original Array after modifying its VIEW:(2nd member (2) changed): [ 1 32  3  4  5]
Original Array after modifying its COPY: [1 2 3 4 5]
The COPY itself changed: [345   2   3   4   5]

**Assignment 33 — Week 3, Day 3**

**Topic: NumPy**

NumPy array shape.

In [ ]:
array_1D = np.array([10, 20, 30, 40, 50, 60, 70])
print("1D Array:Shape:", array_1D.shape)
array_2D = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D Array:Shape:", array_2D.shape)
array_3D = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("3D Array:Shape:", array_3D.shape)

1D Array:Shape: (7,)
2D Array:Shape: (2, 3)
3D Array:Shape: (2, 2, 2)

**Assignment 34 — Week 3, Day 3**

**Topic: NumPy**

NumPy array reshaping.

In [ ]:
arr1D=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("1D Array:",arr1D)
reshaped_2D = arr1D.reshape(3, 4)
print("Reshaped 1D to 2D Array:\n", reshaped_2D)
reshaped_3D = arr1D.reshape(2, 2, 3)
print("Reshaped to 3D Array:\n", reshaped_3D)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 1D to 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

**Assignment 35 — Week 3, Day 3**

**Topic: NumPy**

NumPy array iteration.

In [ ]:
import numpy as np
namesList = np.array(['Fatima', 'Mamoona', 'Rida'])
print("Iterate through 1D array:",namesList)
for name in namesList:
  print('Hello! ' + name)

array_2D=arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Iterate through 2D array row by row:")
#print("Iterate through 2D array:",array_2D)
for row in array_2D:
    print(row)

print("Iterate on each element of 2D array:")
for row in array_2D:
    for element in row:
        print(element)

arr_3d = np.array([[[11, 12, 13], [14, 15, 16]], [[17, 18, 19], [20, 21, 22]]])
print("Iterate through 3D array:")
for row in arr_3d:
  print(row)

Iterate through 1D array: ['Fatima' 'Mamoona' 'Rida']
Hello! Fatima
Hello! Mamoona
Hello! Rida
Iterate through 2D array row by row:
[1 2 3]
[4 5 6]
Iterate on each element of 2D array:
1
2
3
4
5
6
Iterate through 3D array:
[[11 12 13]
 [14 15 16]]
[[17 18 19]
 [20 21 22]]

**Assignment 36 — Week 3, Day 4**

**Topic: NumPy**

Joining NumPy matrices/arrays.

In [ ]:
num_arr1 = np.array([[1, 2], [3, 4]])
num_arr2 = np.array([[5, 6], [7, 8]])

concat_arr = np.concatenate((num_arr1, num_arr2), axis=1)
print("concatenate arrays along rows:",concat_arr)

# horizontal joining using hstack
hstack = np.hstack((num_arr1, num_arr2))
print("Horizongtal Joining:",hstack)

# vertical joining using vstack
vstack = np.vstack((num_arr1, num_arr2))
print("Vertical Joining:",vstack)

concatenate arrays along rows: [[1 2 5 6]
 [3 4 7 8]]
Horizongtal Joining: [[1 2 5 6]
 [3 4 7 8]]
Vertical Joining: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

**Assignment 37 — Week 3, Day 4**

**Topic: NumPy**

Splitting NumPy arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the 1D array into 3 equal sub-arrays
subarrays = np.split(arr, 3)

print("Sub Arrays:",subarrays)

Sub Arrays: [array([1, 2]), array([3, 4]), array([5, 6])]

**Assignment 38 — Week 3, Day 4**

**Topic: NumPy**

Searching NumPy arrays.

In [ ]:
array = np.array([1, 2, 3, 4, 5, 5, 3, 6])
print("Search Array:",array)

search = np.where(array == 3)#return the indexes, where element=3
print("Indexes where element=3:",search)

evenSearch= np.where(array % 2 == 0)
print("Indexes where element=even:",evenSearch)

ans=np.searchsorted(array, 6) #elment 6 is at index 7
print("Indexes where element=6:",ans)

Search Array: [1 2 3 4 5 5 3 6]
Indexes where element=3: (array([2, 6]),)
Indexes where element=even: (array([1, 3, 7]),)
Indexes where element=6: 7

**Assignment 39 — Week 3, Day 4**

**Topic: NumPy**

Sorting NumPy arrays.

In [ ]:
originalArray = np.array([3, 2, 0, 1, 4])
print("Orginal Array:",originalArray)
print("Array After Sort:",np.sort(originalArray))

fruitsListOriginal = np.array(['mango', 'banana', 'apple'])
print("Fruits:Orginal Array:",fruitsListOriginal)
print("Array After Sort:",np.sort(fruitsListOriginal))

array_2D = np.array([[5, 2, 4], [3, 2, 1]])
print("Sort 2D Array:",np.sort(array_2D))

Orginal Array: [3 2 0 1 4]
Array After Sort: [0 1 2 3 4]
Fruits:Orginal Array: ['mango' 'banana' 'apple']
Array After Sort: ['apple' 'banana' 'mango']
Sort 2D Array: [[2 4 5]
 [1 2 3]]

**Assignment 40 — Week 3, Day 3**

**Topic: NumPy**

NumPy random techniques.

In [ ]:
from numpy import random

random_Int= random.randint(10)
print("Generate random integer from 0 to 10:",random_Int)

random_Float = random.random()
print("Random Float from 0-1:", random_Float)

shapes = ["triangle", "rectangle", "square", "circle"]
random_choice = random.choice(shapes)
print("Random Choice from List:", random_choice)

Generate random integer from 0 to 10: 8
Random Float from 0-1: 0.10377612664785962
Random Choice from List: square

**Assignment 41 — Week 3, Day 5**

**Topic: Pandas**

Pandas basics tutorial exercise.

In [ ]:
import pandas as pd

df = pd.read_csv('calories.csv')
df.head(5)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

**Assignment 42 — Week 3, Day 5**

**Topic: Pandas**

Complete the Pandas installation/getting-started exercise.

In [ ]:
#pip install pandas
import pandas as pd
print("Pandas Version:",pd.__version__)

Pandas Version: 2.2.3

**Assignment 43 — Week 3, Day 5**

**Topic: Pandas**

Pandas Series.

In [ ]:
import pandas as pd
print("Pandas Series:")

series = pd.Series([10, 20, 30, 40])
print(series)

Pandas Series:
0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
print("First Element:",series[0])  #Access value by index:First value: 10
print("Sum:",series.sum())

First Element: 10
Sum: 100

**Assignment 44 — Week 3, Day 5**

**Topic: Pandas**

Create Pandas DataFrames.

In [ ]:
sudent_data = {
    "Name": ["Fatima", "Rabia", "Faiza", "Mariyam"],
    "Age": [14, 15, 13, 16],
    "Marks": [85, 90, 75, 95]
}

# Load data into a DataFrame object
df = pd.DataFrame(sudent_data)

print(df)

      Name  Age  Marks
0   Fatima   14     85
1    Rabia   15     90
2    Faiza   13     75
3  Mariyam   16     95

In [ ]:
print(df.loc[0])  #First row data

Name     Fatima
Age          14
Marks        85
Name: 0, dtype: object

In [ ]:
#give name to each row:
df = pd.DataFrame(sudent_data, index = ["Student_1", "Student_2", "Student_3","Student_4"])
df

              Name  Age  Marks
Student_1   Fatima   14     85
Student_2    Rabia   15     90
Student_3    Faiza   13     75
Student_4  Mariyam   16     95

**Assignment 45 — Week 3, Day 5**

**Topic: Pandas**

Opening/reading CSV files with Pandas.

In [ ]:
import pandas as pd
df=pd.read_csv("calories.csv")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
print("MaxRows:",pd.options.display.max_rows)

MaxRows: 60

In [ ]:
df.tail() #show last 5 rows

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4